/**
 * Generated by tsnapi — public API snapshot of `fuzzysort2`
 */
// #region Interfaces
export interface FieldDefinition<T> {
  readonly key: string;
  readonly extract: (_: T) => string | PreparedTarget | null | undefined;
}
export interface FieldMatch extends Match {
  readonly key: string;
}
export interface HighlightableMatch {
  readonly target: string;
  readonly ranges: readonly MatchRange[];
}
export interface Match extends HighlightableMatch {
  readonly score: number;
}
export interface MatchRange {
  readonly start: number;
  readonly end: number;
}
export interface MatchSegment {
  readonly text: string;
  readonly matched: boolean;
}
export interface PreparedTarget {
  readonly target: string;
}
export interface RecordMatch<T> {
  readonly value: T;
  readonly score: number;
  readonly fields: readonly FieldMatch[];
}
export interface SearchOptions {
  readonly limit?: number;
  readonly threshold?: number;
}
export interface SearchResult<TMatch> {
  readonly items: readonly TMatch[];
  readonly total: number;
}
export interface ValueMatch<T> extends Match {
  readonly value: T;
}
// #endregion

// #region Functions
export declare function highlight(_: HighlightableMatch, _?: {
  open?: string;
  close?: string;
}): string;
export declare function match(_: string, _: string | PreparedTarget): Match | null;
export declare function prepare(_: string): PreparedTarget;
export declare function search(_: string, _: readonly (string | PreparedTarget)[], _?: SearchOptions): SearchResult<Match>;
export declare function searchBy<T>(_: string, _: readonly T[], _: (_: T) => string | PreparedTarget | null | undefined, _?: SearchOptions): SearchResult<ValueMatch<T>>;
export declare function searchFields<T>(_: string, _: readonly T[], _: readonly FieldDefinition<T>[], _?: SearchOptions): SearchResult<RecordMatch<T>>;
export declare function segments(_: HighlightableMatch): readonly MatchSegment[];
// #endregion